import {
  BsArrowDownShort,
  BsArrowReturnLeft,
  BsArrowRight,
  BsArrowUp,
  BsArrowUpRight,
  BsBraces,
  BsChatQuoteFill,
  BsCheck2,
  BsCheck2Circle,
  BsChevronDown,
  BsClipboard,
  BsCodeSlash,
  BsCodeSquare,
  BsCommand,
  BsCpu,
  BsCupHot,
  BsDownload,
  BsEnvelope,
  BsFileEarmarkZip,
  BsFileEarmarkZipFill,
  BsFiletypeCss,
  BsFiletypeHtml,
  BsFiletypeJs,
  BsFiletypeJsx,
  BsFiletypePy,
  BsGit,
  BsGithub,
  BsGrid,
  BsHouse,
  BsInstagram,
  BsLightbulb,
  BsLightningCharge,
  BsLinkedin,
  BsList,
  BsMortarboard,
  BsPeople,
  BsPerson,
  BsPlayCircle,
  BsRocketTakeoff,
  BsSearch,
  BsSend,
  BsSignpostSplit,
  BsWind,
  BsXLg,
} from 'react-icons/bs'

// Bootstrap Icons (icons.getbootstrap.com).
// Only the icons listed here get bundled, which keeps the site small.
// To add one: import it above, then add it to this list with its Bootstrap name.
const icons = {
  'arrow-down-short': BsArrowDownShort,
  'arrow-return-left': BsArrowReturnLeft,
  'arrow-right': BsArrowRight,
  'arrow-up': BsArrowUp,
  'arrow-up-right': BsArrowUpRight,
  braces: BsBraces,
  'chat-quote-fill': BsChatQuoteFill,
  check2: BsCheck2,
  'check2-circle': BsCheck2Circle,
  'chevron-down': BsChevronDown,
  clipboard: BsClipboard,
  'code-slash': BsCodeSlash,
  'code-square': BsCodeSquare,
  command: BsCommand,
  cpu: BsCpu,
  'cup-hot': BsCupHot,
  download: BsDownload,
  envelope: BsEnvelope,
  'file-earmark-zip': BsFileEarmarkZip,
  'file-earmark-zip-fill': BsFileEarmarkZipFill,
  'filetype-css': BsFiletypeCss,
  'filetype-html': BsFiletypeHtml,
  'filetype-js': BsFiletypeJs,
  'filetype-jsx': BsFiletypeJsx,
  'filetype-py': BsFiletypePy,
  git: BsGit,
  github: BsGithub,
  grid: BsGrid,
  house: BsHouse,
  instagram: BsInstagram,
  lightbulb: BsLightbulb,
  'lightning-charge': BsLightningCharge,
  linkedin: BsLinkedin,
  list: BsList,
  mortarboard: BsMortarboard,
  people: BsPeople,
  person: BsPerson,
  'play-circle': BsPlayCircle,
  'rocket-takeoff': BsRocketTakeoff,
  search: BsSearch,
  send: BsSend,
  'signpost-split': BsSignpostSplit,
  wind: BsWind,
  'x-lg': BsXLg,
}

// Usage: <Icon name="github" />
function Icon({ name, className = '', ...rest }) {
  const IconSvg = icons[name]
  if (!IconSvg) return null

  // aria-hidden: icons are decoration, screen readers skip them
  return <IconSvg className={`bi ${className}`.trim()} aria-hidden="true" focusable="false" {...rest} />
}

export default Icon
